apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy
  namespace: istio-study

data:
  httpbin.conf: |
    server {
        listen 80;

        server_name localhost;

        access_log  /var/log/nginx/access.log;
        error_log  /var/log/nginx/error.log;

        # add_header 'Access-Control-Allow-Origin' '*';

        location / {
            # rewrite /foo/(.*) /$1  break;
            proxy_pass         http://local-docker-httpbin:8001;
            proxy_ssl_verify   off;
            proxy_redirect     off;

            proxy_set_header   Host             $http_host;
            proxy_set_header   X-Real-IP        $remote_addr;
            proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
        }
    }