apiVersion: v1
kind: Endpoints
metadata:
  name: local-docker-httpbin
  namespace: istio-study
subsets:
  - addresses:
      - ip: 198.19.249.3
    ports:
      - port: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: local-docker-httpbin
  namespace: istio-study
spec:
  type: NodePort
  ports:
    - port: 8001
#      nodePort: 30001
      targetPort: 8001

