apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
#    - 198.19.249.34/24
#    - 198.19.249.34/24
    - 198.19.249.35-198.19.249.40
#    - 198.19.249.1-198.19.249.2

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: first-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - first-pool