apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv
  namespace: istio-study
spec:
  storageClassName: local
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/middleware-mysql"